# Generated by Django 2.2.6 on 2019-10-17 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComments',
            new_name='UserComment',
        ),
    ]
